[__config__]
oldver = "oldver.json"
newver = "newver.json"

## PACKAGES ##
[cartero]
source = "git"
git = "https://github.com/danirod/cartero"
prefix = "v"
exclude_regex = ".*(beta).*"
[i386-elf-binutils]
source = "regex"
url = "https://ftp.gnu.org/gnu/binutils/"
regex = "binutils-([0-9.]+).tar.xz"
[i386-elf-gcc]
source = "regex"
url = "https://ftp.gnu.org/gnu/gcc/"
regex = "gcc-([0-9.]+)/"
