[__config__]
oldver = "oldver.json"
newver = "newver.json"

## PACKAGES ##
[cartero]
source = "git"
git = "https://github.com/danirod/cartero"
prefix = "v"
exclude_regex = ".*(beta).*"
[i386-elf-binutils]
source = "regex"
url = "https://ftp.gnu.org/gnu/binutils/"
regex = "binutils-([0-9.]+).tar.xz"
[i386-elf-gcc]
source = "regex"
url = "https://ftp.gnu.org/gnu/gcc/"
regex = "gcc-([0-9.]+)/"
[i386-elf-gdb]
source = "git"
git = "https://sourceware.org/git/binutils-gdb.git"
include_regex = "gdb-.*-release"
prefix = "gdb-"
[nordzy-icon-theme]
source = "git"
git = "https://github.com/MolassesLover/Nordzy-icon"
[python-mastodon]
source = "pypi"
pypi = "Mastodon.py"
[python-xmlformatter]
source = "pypi"
pypi = "xmlformatter"
[tootstream]
source = "git"
git = "https://github.com/magicalraccoon/tootstream"
prefix = "v"
exclude_regex = ".*(beta).*"
[ttf-chakra-petch]
source = "git"
git = "https://github.com/cadsondemak/chakra-petch"
use_commit = true
